# Generated by Django 3.1.5 on 2021-01-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name_plural': 'Social Media Icons'},
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='on',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
