# Generated by Django 3.1.5 on 2021-03-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='on',
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(choices=[('fa-instagram', 'Instagram'), ('fa-facebook-f', 'Facebook'), ('fa-tiktok', 'Tiktok'), ('fa-pinterest-p', 'Pintereset'), ('fa-youtube', 'Youtube'), ('fa-snapchat-ghost', 'Snapchat'), ('fa-twitter', 'Twitter')], max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.TextField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'Tiktok'), ('pinterest', 'Pintereset'), ('youtube', 'Youtube'), ('snapchat', 'Snapchat'), ('twitter', 'Twitter')], max_length=254),
        ),
    ]
