# Generated by Django 3.1.5 on 2021-03-30 06:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('friendly_name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True)),
                ('friendly_name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Collection Names',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True, unique=True)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('url', models.URLField(max_length=1024, null=True)),
                ('main_img', models.BooleanField(default=False)),
                ('room_view', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Artwork Images',
            },
        ),
        migrations.CreateModel(
            name='ImagesFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True, unique=True)),
                ('imgs', models.ManyToManyField(to='products.Image')),
            ],
            options={
                'verbose_name_plural': 'Images Folders',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('friendly_name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, null=True, unique=True)),
                ('friendly_name', models.CharField(max_length=254, null=True)),
                ('description', models.TextField(max_length=800, null=True)),
                ('author', models.CharField(max_length=254, null=True)),
                ('dimensions', models.CharField(max_length=70, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('sku', models.CharField(max_length=254, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('collection_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.collection')),
                ('images_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.imagesfolder')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.tag')),
            ],
        ),
    ]
