# Generated by Django 3.1.5 on 2021-03-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210328_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
