# Generated by Django 3.1.5 on 2021-01-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210122_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagesfolder',
            name='imgs',
        ),
        migrations.AddField(
            model_name='imagesfolder',
            name='imgs',
            field=models.ManyToManyField(blank=True, null=True, to='products.Image'),
        ),
    ]
