# Generated by Django 3.1.5 on 2021-01-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210123_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesfolder',
            name='imgs',
            field=models.ManyToManyField(to='products.Image'),
        ),
    ]
