# Generated by Django 3.1.5 on 2021-03-28 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210328_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='show_in_gallery',
        ),
        migrations.RemoveField(
            model_name='image',
            name='show_in_new',
        ),
    ]
