# Generated by Django 3.1.5 on 2021-01-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210123_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name_plural': 'Collection Names'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name_plural': 'Artwork Images'},
        ),
        migrations.AlterModelOptions(
            name='imagesfolder',
            options={'verbose_name_plural': 'Images Folders'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_url',
            new_name='url',
        ),
    ]
